dashboard:
  408576714243833867: admin    # Harry - change this

guild_configuration:
  permission_levels:
    roles:
      owner: 631112088282071060
      administrator: 631112198751649801
      moderator: 631112356079861810
    users:
      667684156385394711: 90  # HarTex

bot_interface:
  command_prefix: '.'
  guild_nickname: '(.) HarTex'

plugins:
  moderation:
    permission_level_required: 70
    commands:
      kick:
        general:
          enabled: False
        function:
          enable_dm: True

      ban:
        general:
          enabled: True
        function:
          enable_dm: True
      unban:
        general:
          enabled: True
        function:
          enable_dm: True

      ceasech:
        general:
          enabled: True

      unceasech:
        general:
          enabled: True

      mute:
        general:
          enabled: True
        function:
          muted_role: 631114297954533384

      unmute:
        general:
          enabled: True
        function:
          muted_role: 631114297954533384

      tempmute:
        general:
          enabled: True
        function:
          muted_role: 631114297954533384

      ceasegd:
        general:
          enabled: True

      unceasegd:
        general:
          enabled: True

  censorship: # You are advised to a malicious domains, radical slurs and offensive words in this plugin.
    permission_levels:
      45:
        punishment:
          type: TEMPMUTE
          duration: 300
        settings:
          zalgo:
            filter: True
            filer_nicknames: True
          invites:
            filter: True
            invites_whitelist: [] # add the servers you want to whitelist here
          domains:
            filter: True
            domains_whitelist: [] # add the domains you want to whitelist here
          blocked:
            words: [] # add the words you want to censor here
            nicknames: [] # add the nicknames you want to censor here

  antispam:
    permission_levels:
      45:
        punishment:
          type: TEMPMUTE
          duration: 300
        removal: True
        channel_whitelist: [] # add the channels you want antispam to be disabled here

  logging:
    type:
      member_log:
        channel: 673431030744612885 # member-logs
        actions:
          - MEMBER_JOIN
          - MEMBER_LEFT
        mode: pretty
        timestamps:
          enabled: True
          timezone: GMT+0
      message_log:
        channel: 631119063539515402 # message-logs
        actions:
          - MESSAGE_EDIT
          - MESSAGE_DELETE
          - MESSAGE_BULK_DELETE
        mode: pretty
        timestamps:
          enabled: True
          timezone: GMT+0
      moderation_log:
        channel: 672785114727448589 # moderation-logs
        actions:
          - MEMBER_KICKED
          - MEMBER_BANNED
          - MEMBER_UNBANNED
          - MEMBER_TEMPBAN
          - MEMBER_SOFTBAN
          - CHANNEL_CEASED
          - CHANNEL_UNCEASED
          - GUILD_CEASED
          - GUILD_UNCEASED
          - CHANNEL_CREATE
          - CHANNEL_EDIT
          - CHANNEL_DELETE
        timestamps:
          enabled: True
          timezone: GMT+0
